FROM nginx:latest

## Install python and pip
RUN apt-get update && apt-get install -y \
    python-dev \
    python-pip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip install mkdocs mkdocs-material pygments>=2.2 pymdown-extensions>=2.0
RUN mkdir -p /tmp/mkdocs
WORKDIR /tmp/mkdocs
ADD ./docs /tmp/mkdocs/docs
ADD ./mkdocs.yml /tmp/mkdocs/
RUN ls -la /tmp/mkdocs/ && mkdocs build
RUN cp -r site/* /usr/share/nginx/html/
